<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{{ asset('assets/app-assets/vendors/js/vendors.min.js') }}"></script>
<script src="{{ asset('assets/app-assets/vendors/js/charts/chart.min.js') }}"></script>
<script src="{{ asset('assets/app-assets/vendors/js/charts/raphael-min.js') }}"></script>
<script src="{{ asset('assets/app-assets/vendors/js/charts/morris.min.js') }}"></script>
<script src="{{ asset('assets/app-assets/vendors/js/charts/jvector/jquery-jvectormap-2.0.3.min.js') }}"></script>
<script src="{{ asset('assets/app-assets/vendors/js/charts/jvector/jquery-jvectormap-world-mill.js') }}"></script>
<script src="{{ asset('assets/app-assets/js/core/app-menu.js') }}"></script>
<script src="{{ asset('assets/app-assets/js/core/app.js') }}"></script>
<script src="//cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
